feat: add error popup during failed or long loading screens
decentraland/explorer-desktop pull request #34
Opened 2021-11-23 20:21 UTC by Kinerius

## What does this PR change?

Fixes https://github.com/decentraland/unity-renderer/issues/1492
...

## How to test the changes?

1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:{branch_name}&{desired_url_params}
2. ...

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2021-11-24 18:50 UTC, kuruk-mm requested changes

2021-11-24 18:55 UTC, Kinerius commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Utils/DesktopUtils.cs
> +            Application.Quit();
Done

2021-11-24 20:00 UTC, kuruk-mm approved these changes

2021-11-24 20:00 UTC, kuruk-mm approved these changes

2021-11-24 20:00 UTC, kuruk-mm commented on unity-renderer-desktop/Packages/manifest.json
> +{ "dependencies": { "com.coffee.git-dependency-resolver": "https://github.com/mob-sakai/GitDependencyResolverForUnity.git", "com.decentraland.unity-renderer": "git+https://github.com/decentraland/uni
update version to master before merging

2021-11-24 20:39 UTC, RominaMarchetti approved these changes

2021-11-24 23:22 UTC, kuruk-mm requested changes

2021-11-24 23:22 UTC, kuruk-mm commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/LoadingFlow/LoadingFlowController.cs
> +                Dispose();
Do we really want to `Dispose()` the controller here?

2021-11-24 23:22 UTC, kuruk-mm commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/LoadingFlow/LoadingFlowController.cs
> +            view.Hide();
We're hiding the view `gameObject.SetActive(false);` in the constructor and after we never do an `gameObject.SetActive(true);`

2021-11-25 19:01 UTC, Kinerius commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/LoadingFlow/LoadingFlowController.cs
> +            view.Hide();
Solved

2021-11-25 19:03 UTC, Kinerius commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/LoadingFlow/LoadingFlowController.cs
> +                Dispose();
What do you suggest? the only job of this class is to show the error on timeout and then stop working

2021-12-06 15:04 UTC, merged