feat: av pro implementation
decentraland/explorer-desktop pull request #372
Opened 2022-08-24 03:00 UTC by dalkia

## What does this PR change?

## How to test the changes?

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2022-09-01 12:21 UTC, Antivortex approved these changes

2022-09-01 12:21 UTC, Antivortex commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
> +            if (featureFlags.Get().IsFeatureEnabled("use_avpro_player") && Application.platform != RuntimePlatform.LinuxPlayer)
Maybe these combined condition could be embedded into some AVPro wrapper class or even polymorphic video player class with a factory

2022-09-01 12:43 UTC, kwspgoliasz requested changes
The feature appears to be implemented correctly on the Windows App.
Both the videos and audio are correctly displayed, however, in some cases it can take a while for the video to load (ex. Art Week's Metaboralis area).

On the Mac version of the app, small images with motion tend to be displayed correctly, however, in case of larger movies (especially on big screens), the videos either do not load, or get permanently frozen. This is especially visible in the DG Arena scene.

2022-09-07 14:34 UTC, kwspgoliasz commented
The fixes for the Mac resulted in noticeable improvements. The issue with the permanent video freeze is no longer present, however, short freezes for the more demanding videos can still be noticed. When the issue occurs, the video is always resumed after the freeze which lasts for about 10 sec.. This issue is most prominent in the Makersplace (55,62) and at the DG Arena (-118,120) for the corner screens.  
Additionally, an issue with the video not loading at all occurred at the Art Week Main Building area (62,61) and for some objects in the Meta Borealis (55,65).

2022-09-07 20:35 UTC, dalkia commented
Art week building video is not supported by the mac codec

2022-10-19 12:17 UTC, AjimenezDCL requested changes
Great job, super clean. I just left some smal requestes

2022-10-19 12:17 UTC, AjimenezDCL commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Components/Video/AvPro/AvProVideoPlayer.cs
> +    private IEnumerator ResizeVideoTexture()
We can use a task here

2022-10-20 14:35 UTC, kwspgoliasz requested changes
Most of the videos are properly displayed on both, the MacOS and Windows clients, however, some issues are still present.

The issue with some videos not loading can be observed in the following locations:

- DG Arena - screens at the center of the hall and on specific floors - https://user-images.githubusercontent.com/110464313/196973942-5a8e36a8-ac48-4c2f-920e-a8569ae44fd2.mp4.

- Wilderness - the tutorial video - https://user-images.githubusercontent.com/110464313/196974130-0528243e-bde5-4ae3-8fc3-f88cb1c0990c.mp4.

- Filmrare - the cinema screen - https://user-images.githubusercontent.com/110464313/196973975-dd925fa3-857c-4516-ae68-e95af11d98e4.mp4.

Moreover, many of the videos on MacOS suffer from white screen flashing. On the Windows client, the issue occurs only for the VVSVS scene - https://user-images.githubusercontent.com/110464313/196974221-b4c68d5e-e316-467d-bdee-c917a1230455.mp4. 
Slight freezing can be observed when watching the videos on the Mac, however, this might be caused by MacBook's low-end hardware.

Additionally, some of the videos may sometimes require a longer loading time. This issue was observed exclusively in the Art Week area - https://user-images.githubusercontent.com/110464313/196975174-8e9567f0-63e7-451a-96b0-b58ee16f65ec.mp4.

2022-10-20 20:04 UTC, dalkia commented
> Most of the videos are properly displayed on both, the MacOS and Windows clients, however, some issues are still present.
> 
> The issue with some videos not loading can be observed in the following locations:
> 
> * DG Arena - screens at the center of the hall and on specific floors - https://user-images.githubusercontent.com/110464313/196973942-5a8e36a8-ac48-4c2f-920e-a8569ae44fd2.mp4.
> * Wilderness - the tutorial video - https://user-images.githubusercontent.com/110464313/196974130-0528243e-bde5-4ae3-8fc3-f88cb1c0990c.mp4.
> * Filmrare - the cinema screen - https://user-images.githubusercontent.com/110464313/196973975-dd925fa3-857c-4516-ae68-e95af11d98e4.mp4.
> 
> Moreover, many of the videos on MacOS suffer from white screen flashing. On the Windows client, the issue occurs only for the VVSVS scene - https://user-images.githubusercontent.com/110464313/196974221-b4c68d5e-e316-467d-bdee-c917a1230455.mp4. Slight freezing can be observed when watching the videos on the Mac, however, this might be caused by MacBook's low-end hardware.
> 
> Additionally, some of the videos may sometimes require a longer loading time. This issue was observed exclusively in the Art Week area - https://user-images.githubusercontent.com/110464313/196975174-8e9567f0-63e7-451a-96b0-b58ee16f65ec.mp4.

The three videos mentioned (Wilderness, Center video in DG Arena and Filmrare cinema) have been taken down. They are not working either in prd in webgl.

2022-10-24 08:06 UTC, AjimenezDCL approved these changes

2022-10-24 08:06 UTC, AjimenezDCL commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Components/Video/AvPro/AvProVideoPlayer.cs
> +    private CancellationTokenSource resizeVideoTextureCancellationSource;
```suggestion
    private CancellationTokenSource resizeVideoTextureCts;
```

the `Cts` acronym is widely accepted for CancellationTokenSource. I leave it up to you if you prefer the long name.

2022-10-24 16:40 UTC, merged