feat: video streaming ffmpeg
decentraland/explorer-desktop pull request #40
Opened 2021-12-08 14:00 UTC by kuruk-mm

## What does this PR change?

Fix decentraland/unity-renderer#413

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2021-12-08 21:41 UTC, kuruk-mm commented
After the CI passes:

This branch can be downloaded with the following instructions:
### For Windows:
Execute the following commands in `Windows PowerShell`
```bash
# Download
curl -o unity-renderer-windows.zip https://renderer-artifacts.decentraland.org/desktop/feat/video-streaming-ffmpeg/unity-renderer-windows.zip

# Unzip
Expand-Archive -Path unity-renderer-windows.zip -DestinationPath unity-renderer-windows -Force
```
### For Mac:
Execute the following commands:
```bash
# Download
curl -o unity-renderer-mac.zip https://renderer-artifacts.decentraland.org/desktop/feat/video-streaming-ffmpeg/unity-renderer-mac.zip

# Unzip
unzip unity-renderer-mac.zip -d unity-renderer-mac
```
### For Linux: 
Execute the following commands:
```bash
# Download
curl -o unity-renderer-linux.zip https://renderer-artifacts.decentraland.org/desktop/feat/video-streaming-ffmpeg/unity-renderer-linux.zip

# Unzip
unzip unity-renderer-linux.zip -d unity-renderer-linux
```

2021-12-09 19:32 UTC, Kinerius approved these changes
Good work!

2021-12-09 19:32 UTC, Kinerius commented on unity-renderer-desktop/Assets/Plugins/FFMPEGDecoderPlugin/Example/FFMPEGPlayer.cs
> +            Material material = GetComponent<MeshRenderer>().sharedMaterial;
I know that this is going to be called once, but it`s still weird to see a GetComponent on an Update() call, I would move it to the Awake.

2021-12-14 12:56 UTC, kuruk-mm commented on unity-renderer-desktop/Assets/Plugins/FFMPEGDecoderPlugin/Example/FFMPEGPlayer.cs
> +            Material material = GetComponent<MeshRenderer>().sharedMaterial;
This is an example of how to use the FFMPEGPlayer. It's not used at all in the build.

2021-12-14 17:48 UTC, Kinerius requested changes
Nice work! 
Some classes can be deleted since they are empty

2021-12-14 17:48 UTC, Kinerius commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTextureDesktop.cs
> +
This class can be deleted, right?

2021-12-14 17:48 UTC, Kinerius commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/WorldRuntime/RuntimeComponentFactoryDesktop/RuntimeComponentFactoryDesktop.cs
> +
Another empty class

2021-12-14 17:48 UTC, Kinerius commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Environment/Factories/WorldRuntimeContextFactoryDesktop/WorldRuntimeContextFactoryDesktop.cs
> +                componentFactory: new RuntimeComponentFactoryDesktop(poolableComponentFactory));
If you delete `RuntimeComponentFactoryDesktop` this whole class can also be deleted, since we are not overriding any other WorldRuntimeContext component

2021-12-14 18:25 UTC, lorux0 approved these changes

2021-12-14 18:25 UTC, lorux0 commented on unity-renderer-desktop/Assets/Plugins/FFMPEGDecoderPlugin/Example/FFMPEGPlayer.cs
> +public class FFMPEGPlayer : MonoBehaviour
in case this is an usage example i would remove it, since it might produce coding misslead and/or unused code maintenance

2021-12-14 18:25 UTC, lorux0 commented on unity-renderer-desktop/Assets/Plugins/FFMPEGDecoderPlugin/Scripts/FFMPEGDecoder.cs
> +	public class FFMPEGDecoder : IDisposable
formatting in this class looks weird, run IDE auto-format

2021-12-16 16:29 UTC, BrianAmadori commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
> +            DCLVideoTexture.videoPluginWrapperBuilder = () => new VideoPluginWrapper_FFMPEG();
Just FYI: this static func is actually a workaround to make tests work, ideally we should make another component and override the factory. I'm not requesting change because its good enough for now, but we'll have to change it in the future.

2021-12-16 16:30 UTC, BrianAmadori approved these changes
Didn't test but LGTM codewise. It's great that we managed to implement this without having to modify the component video player logic.

2021-12-17 12:27 UTC, kuruk-mm commented on unity-renderer-desktop/Assets/Plugins/FFMPEGDecoderPlugin/Example/FFMPEGPlayer.cs
> +public class FFMPEGPlayer : MonoBehaviour
The folder `FFMPEGDecoderPlugin` is an external code like we have in `unity-renderer`:

https://github.com/decentraland/unity-renderer/tree/master/unity-renderer/Plugins/websocket-sharp-master

The source code is here: https://github.com/decentraland/FFMPEGMediaDecoder

2021-12-22 13:33 UTC, merged