Feat: Added FPS cap
decentraland/explorer-desktop pull request #404
Opened 2022-10-31 17:33 UTC by 0xD-Fabio

## What does this PR change?

...

## How to test the changes?

1. Go to: https://renderer-artifacts.decentraland.org/desktop/index.html?dcl://DESKTOP-BRANCH={branch_name}
2. ...

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2022-11-03 10:54 UTC, AjimenezDCL approved these changes

2022-11-03 13:07 UTC, Kinerius requested changes

2022-11-03 13:07 UTC, Kinerius commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/FPSLimitControlController.cs
> +            Application.targetFrameRate = useFPSCap ? 30 : MAX_FPS;
Why 30? we should give users the option to set a preset number (30,60,144,etc..), 240 is too much for some powerful PCs maybe they just want 60, or 144 for some high refresh rate monitors, not 30.

2022-11-03 13:37 UTC, 0xD-Fabio commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/FPSLimitControlController.cs
> +            Application.targetFrameRate = useFPSCap ? 30 : MAX_FPS;
Since the Task does not specify which options should be possible, I interpreted  "FPS cap" as a boolean toggle.
Who I should ask for a more specific UX clarification?

2022-11-03 13:40 UTC, Kinerius commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/FPSLimitControlController.cs
> +            Application.targetFrameRate = useFPSCap ? 30 : MAX_FPS;
@AjimenezDCL WDYT?

2022-11-03 13:52 UTC, aixaCode commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/FPSLimitControlController.cs
> +            Application.targetFrameRate = useFPSCap ? 30 : MAX_FPS;
I agree with @Kinerius. I would give predefined options like 30, 60, 90, 120, 144, 240 We could have a drop-down menu, or toggle between them

2022-11-03 16:59 UTC, 0xD-Fabio commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/FPSLimitControlController.cs
> +            Application.targetFrameRate = useFPSCap ? 30 : MAX_FPS;
Ok, I'll make a dropdown; thanks for the input!

2022-11-07 14:38 UTC, aixaCode commented on unity-renderer-desktop/Assets/Scenes/MainScene.unity
> +  network: 0
Probably we don't need those changes in this PR?

2022-11-14 17:00 UTC, 0xD-Fabio commented on unity-renderer-desktop/Assets/Scenes/MainScene.unity
> +  network: 0
reverted back to original scene

2022-11-14 17:03 UTC, 0xD-Fabio commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsPanelHUDDesktop/Scripts/FPSLimitControlController.cs
> +            Application.targetFrameRate = useFPSCap ? 30 : MAX_FPS;
I finally fixed the error I made and pushed the dropdown menu with all the options.

2022-11-15 14:29 UTC, Kinerius approved these changes
Works as expected, Good Job!

2022-11-16 09:04 UTC, merged