fix: crash and freeze
decentraland/explorer-desktop pull request #83
Opened 2022-02-04 15:54 UTC by Kinerius

## What does this PR change?

Fixes a random crash caused by FFMPEG decoder

Also fixed Unity forced SSL and port

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

2022-02-04 18:42 UTC, nlorux requested changes

2022-02-04 18:42 UTC, nlorux commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
> +                withSSL = false;
this makes sense.. however you could remove `Web Socket SSL` from `DebugConfigComponent` ?

2022-02-04 18:44 UTC, nlorux commented
since video streaming is now disabled because it was crashing the app while running through the metaverse, it would be good to confirm this merge with @olavra because before this changes i was able to see at least one video. I know it this issue has to be fixed, but perhaps it can be done in this PR

2022-02-08 13:19 UTC, kuruk-mm requested changes

2022-02-08 13:19 UTC, kuruk-mm commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
> +                withSSL = false;
```suggestion
                withSSL = DebugConfigComponent.i.webSocketSSL;
```

Can you make this change?

2022-02-08 13:21 UTC, Kinerius commented on unity-renderer-desktop/Assets/Scripts/MainScripts/DCL/MainDesktop/MainDesktop.cs
> +                withSSL = false;
Yes! totally agree

2022-02-08 15:50 UTC, pravusjif approved these changes
With this build the never-ending loading scenes issue doesn't happen so it must be provoked by the problems with the FFMPEG plugin, nice catch

2022-02-08 16:17 UTC, merged